#include"common.h"
#include"display.h"

void display(int a,int b,int x,int y)
{
	if(a==0&&b==0){
		puthz(x,y,"清华大学人工智能",24,26,YELLOW);
	}
	if(a==0&&b==1){
		puthz(x,y,"清华大学计算机科学",24,26,YELLOW);
	}	
	if(a==0&&b==2){
		puthz(x,y,"清华大学自动化",24,26,YELLOW);
	}	
	if(a==0&&b==3){
		puthz(x,y,"清华大学电气工程",24,26,YELLOW);
	}	
	if(a==0&&b==4){
		puthz(x,y,"清华大学临床医学",24,26,YELLOW);
	}	
	if(a==0&&b==5){
		puthz(x,y,"清华大学数学",24,26,YELLOW);
	}	
	if(a==0&&b==6){
		puthz(x,y,"清华大学物理",24,26,YELLOW);
	}	
	if(a==0&&b==7){
		puthz(x,y,"清华大学能源工程",24,26,YELLOW);
	}	
	if(a==0&&b==8){
		puthz(x,y,"清华大学机械制造",24,26,YELLOW);
	}	
	if(a==0&&b==9){
		puthz(x,y,"清华大学法学",24,26,YELLOW);
	}	
	if(a==0&&b==10){
		puthz(x,y,"清华大学语言学",24,26,YELLOW);
	}	
	if(a==0&&b==11){
		puthz(x,y,"清华大学哲学",24,26,YELLOW);
	}	
	
	
	
	if(a==1&&b==0){
		puthz(x,y,"北京大学人工智能",24,26,YELLOW);
	}
	if(a==1&&b==1){
		puthz(x,y,"北京大学计算机科学",24,26,YELLOW);
	}	
	if(a==1&&b==2){
		puthz(x,y,"北京大学自动化",24,26,YELLOW);
	}	
	if(a==1&&b==3){
		puthz(x,y,"北京大学电气工程",24,26,YELLOW);
	}	
	if(a==1&&b==4){
		puthz(x,y,"北京大学临床医学",24,26,YELLOW);
	}	
	if(a==1&&b==5){
		puthz(x,y,"北京大学数学",24,26,YELLOW);
	}	
	if(a==1&&b==6){
		puthz(x,y,"北京大学物理",24,26,YELLOW);
	}	
	if(a==1&&b==7){
		puthz(x,y,"北京大学能源工程",24,26,YELLOW);
	}	
	if(a==1&&b==8){
		puthz(x,y,"北京大学机械制造",24,26,YELLOW);
	}	
	if(a==1&&b==9){
		puthz(x,y,"北京大学法学",24,26,YELLOW);
	}	
	if(a==1&&b==10){
		puthz(x,y,"北京大学语言学",24,26,YELLOW);
	}	
	if(a==1&&b==11){
		puthz(x,y,"北京大学哲学",24,26,YELLOW);
	}				
	
	
	if(a==2&&b==0){
		puthz(x,y,"浙江大学人工智能",24,26,YELLOW);
	}
	if(a==2&&b==1){
		puthz(x,y,"浙江大学计算机科学",24,26,YELLOW);
	}	
	if(a==2&&b==2){
		puthz(x,y,"浙江大学自动化",24,26,YELLOW);
	}	
	if(a==2&&b==3){
		puthz(x,y,"浙江大学电气工程",24,26,YELLOW);
	}	
	if(a==2&&b==4){
		puthz(x,y,"浙江大学临床医学",24,26,YELLOW);
	}	
	if(a==2&&b==5){
		puthz(x,y,"浙江大学数学",24,26,YELLOW);
	}	
	if(a==2&&b==6){
		puthz(x,y,"浙江大学物理",24,26,YELLOW);
	}	
	if(a==2&&b==7){
		puthz(x,y,"浙江大学能源工程",24,26,YELLOW);
	}	
	if(a==2&&b==8){
		puthz(x,y,"浙江大学机械制造",24,26,YELLOW);
	}	
	if(a==2&&b==9){
		puthz(x,y,"浙江大学法学",24,26,YELLOW);
	}	
	if(a==2&&b==10){
		puthz(x,y,"浙江大学语言学",24,26,YELLOW);
	}	
	if(a==2&&b==11){
		puthz(x,y,"浙江大学哲学",24,26,YELLOW);
	}				
	
	
	if(a==3&&b==0){
		puthz(x,y,"上海交通大学人工智能",24,26,YELLOW);
	}
	if(a==3&&b==1){
		puthz(x,y,"上海交通大学计算机科学",24,26,YELLOW);
	}	
	if(a==3&&b==2){
		puthz(x,y,"上海交通大学自动化",24,26,YELLOW);
	}	
	if(a==3&&b==3){
		puthz(x,y,"上海交通大学电气工程",24,26,YELLOW);
	}	
	if(a==3&&b==4){
		puthz(x,y,"上海交通大学临床医学",24,26,YELLOW);
	}	
	if(a==3&&b==5){
		puthz(x,y,"上海交通大学数学",24,26,YELLOW);
	}	
	if(a==3&&b==6){
		puthz(x,y,"上海交通大学物理",24,26,YELLOW);
	}	
	if(a==3&&b==7){
		puthz(x,y,"上海交通大学能源工程",24,26,YELLOW);
	}	
	if(a==3&&b==8){
		puthz(x,y,"上海交通大学机械制造",24,26,YELLOW);
	}	
	if(a==3&&b==9){
		puthz(x,y,"上海交通大学法学",24,26,YELLOW);
	}	
	if(a==3&&b==10){
		puthz(x,y,"上海交通大学语言学",24,26,YELLOW);
	}	
	if(a==3&&b==11){
		puthz(x,y,"上海交通大学哲学",24,26,YELLOW);
	}				
	
	
	if(a==4&&b==0){
		puthz(x,y,"复旦大学人工智能",24,26,YELLOW);
	}
	if(a==4&&b==1){
		puthz(x,y,"复旦大学计算机科学",24,26,YELLOW);
	}	
	if(a==4&&b==2){
		puthz(x,y,"复旦大学自动化",24,26,YELLOW);
	}	
	if(a==4&&b==3){
		puthz(x,y,"复旦大学电气工程",24,26,YELLOW);
	}	
	if(a==4&&b==4){
		puthz(x,y,"复旦大学临床医学",24,26,YELLOW);
	}	
	if(a==4&&b==5){
		puthz(x,y,"复旦大学数学",24,26,YELLOW);
	}	
	if(a==4&&b==6){
		puthz(x,y,"复旦大学物理",24,26,YELLOW);
	}	
	if(a==4&&b==7){
		puthz(x,y,"复旦大学能源工程",24,26,YELLOW);
	}	
	if(a==4&&b==8){
		puthz(x,y,"复旦大学机械制造",24,26,YELLOW);
	}	
	if(a==4&&b==9){
		puthz(x,y,"复旦大学法学",24,26,YELLOW);
	}	
	if(a==4&&b==10){
		puthz(x,y,"复旦大学语言学",24,26,YELLOW);
	}	
	if(a==4&&b==11){
		puthz(x,y,"复旦大学哲学",24,26,YELLOW);
	}				
	
					
	if(a==5&&b==0){
		puthz(x,y,"南京大学人工智能",24,26,YELLOW);
	}
	if(a==5&&b==1){
		puthz(x,y,"南京大学计算机科学",24,26,YELLOW);
	}	
	if(a==5&&b==2){
		puthz(x,y,"南京大学自动化",24,26,YELLOW);
	}	
	if(a==5&&b==3){
		puthz(x,y,"南京大学电气工程",24,26,YELLOW);
	}	
	if(a==5&&b==4){
		puthz(x,y,"南京大学临床医学",24,26,YELLOW);
	}	
	if(a==5&&b==5){
		puthz(x,y,"南京大学数学",24,26,YELLOW);
	}	
	if(a==5&&b==6){
		puthz(x,y,"南京大学物理",24,26,YELLOW);
	}	
	if(a==5&&b==7){
		puthz(x,y,"南京大学能源工程",24,26,YELLOW);
	}	
	if(a==5&&b==8){
		puthz(x,y,"南京大学机械制造",24,26,YELLOW);
	}	
	if(a==5&&b==9){
		puthz(x,y,"南京大学法学",24,26,YELLOW);
	}	
	if(a==5&&b==10){
		puthz(x,y,"南京大学语言学",24,26,YELLOW);
	}	
	if(a==5&&b==11){
		puthz(x,y,"南京大学哲学",24,26,YELLOW);
	}					
	
	
	if(a==6&&b==0){
		puthz(x,y,"中国科学技术大学人工智能",24,26,YELLOW);
	}
	if(a==6&&b==1){
		puthz(x,y,"中国科学技术大学计算机科学",24,26,YELLOW);
	}	
	if(a==6&&b==2){
		puthz(x,y,"中国科学技术大学自动化",24,26,YELLOW);
	}	
	if(a==6&&b==3){
		puthz(x,y,"中国科学技术大学电气工程",24,26,YELLOW);
	}	
	if(a==6&&b==4){
		puthz(x,y,"中国科学技术大学临床医学",24,26,YELLOW);
	}	
	if(a==6&&b==5){
		puthz(x,y,"中国科学技术大学数学",24,26,YELLOW);
	}	
	if(a==6&&b==6){
		puthz(x,y,"中国科学技术大学物理",24,26,YELLOW);
	}	
	if(a==6&&b==7){
		puthz(x,y,"中国科学技术大学能源工程",24,26,YELLOW);
	}	
	if(a==6&&b==8){
		puthz(x,y,"中国科学技术大学机械制造",24,26,YELLOW);
	}	
	if(a==6&&b==9){
		puthz(x,y,"中国科学技术大学法学",24,26,YELLOW);
	}	
	if(a==6&&b==10){
		puthz(x,y,"中国科学技术大学语言学",24,26,YELLOW);
	}	
	if(a==6&&b==11){
		puthz(x,y,"中国科学技术大学哲学",24,26,YELLOW);
	}					
	
	
	if(a==7&&b==0){
		puthz(x,y,"华中科技大学人工智能",24,26,YELLOW);
	}
	if(a==7&&b==1){
		puthz(x,y,"华中科技大学计算机科学",24,26,YELLOW);
	}	
	if(a==7&&b==2){
		puthz(x,y,"华中科技大学自动化",24,26,YELLOW);
	}	
	if(a==7&&b==3){
		puthz(x,y,"华中科技大学电气工程",24,26,YELLOW);
	}	
	if(a==7&&b==4){
		puthz(x,y,"华中科技大学临床医学",24,26,YELLOW);
	}	
	if(a==7&&b==5){
		puthz(x,y,"华中科技大学数学",24,26,YELLOW);
	}	
	if(a==7&&b==6){
		puthz(x,y,"华中科技大学物理",24,26,YELLOW);
	}	
	if(a==7&&b==7){
		puthz(x,y,"华中科技大学能源工程",24,26,YELLOW);
	}	
	if(a==7&&b==8){
		puthz(x,y,"华中科技大学机械制造",24,26,YELLOW);
	}	
	if(a==7&&b==9){
		puthz(x,y,"华中科技大学法学",24,26,YELLOW);
	}	
	if(a==7&&b==10){
		puthz(x,y,"华中科技大学语言学",24,26,YELLOW);
	}	
	if(a==7&&b==11){
		puthz(x,y,"华中科技大学哲学",24,26,YELLOW);
	}					
	
			
	if(a==8&&b==0){
		puthz(x,y,"武汉大学人工智能",24,26,YELLOW);
	}
	if(a==8&&b==1){
		puthz(x,y,"武汉大学计算机科学",24,26,YELLOW);
	}	
	if(a==8&&b==2){
		puthz(x,y,"武汉大学自动化",24,26,YELLOW);
	}	
	if(a==8&&b==3){
		puthz(x,y,"武汉大学电气工程",24,26,YELLOW);
	}	
	if(a==8&&b==4){
		puthz(x,y,"武汉大学临床医学",24,26,YELLOW);
	}	
	if(a==8&&b==5){
		puthz(x,y,"武汉大学数学",24,26,YELLOW);
	}	
	if(a==8&&b==6){
		puthz(x,y,"武汉大学物理",24,26,YELLOW);
	}	
	if(a==8&&b==7){
		puthz(x,y,"武汉大学能源工程",24,26,YELLOW);
	}	
	if(a==8&&b==8){
		puthz(x,y,"武汉大学机械制造",24,26,YELLOW);
	}	
	if(a==8&&b==9){
		puthz(x,y,"武汉大学法学",24,26,YELLOW);
	}	
	if(a==8&&b==10){
		puthz(x,y,"武汉大学语言学",24,26,YELLOW);
	}	
	if(a==8&&b==11){
		puthz(x,y,"武汉大学哲学",24,26,YELLOW);
	}					
	
		
	
	if(a==9&&b==0){
		puthz(x,y,"西安交通大学人工智能",24,26,YELLOW);
	}
	if(a==9&&b==1){
		puthz(x,y,"西安交通大学计算机科学",24,26,YELLOW);
	}	
	if(a==9&&b==2){
		puthz(x,y,"西安交通大学自动化",24,26,YELLOW);
	}	
	if(a==9&&b==3){
		puthz(x,y,"西安交通大学电气工程",24,26,YELLOW);
	}	
	if(a==9&&b==4){
		puthz(x,y,"西安交通大学临床医学",24,26,YELLOW);
	}	
	if(a==9&&b==5){
		puthz(x,y,"西安交通大学数学",24,26,YELLOW);
	}	
	if(a==9&&b==6){
		puthz(x,y,"西安交通大学物理",24,26,YELLOW);
	}	
	if(a==9&&b==7){
		puthz(x,y,"西安交通大学能源工程",24,26,YELLOW);
	}	
	if(a==9&&b==8){
		puthz(x,y,"西安交通大学机械制造",24,26,YELLOW);
	}	
	if(a==9&&b==9){
		puthz(x,y,"西安交通大学法学",24,26,YELLOW);
	}	
	if(a==9&&b==10){
		puthz(x,y,"西安交通大学语言学",24,26,YELLOW);
	}	
	if(a==9&&b==11){
		puthz(x,y,"西安交通大学哲学",24,26,YELLOW);
	}					
	
		
	
}
